# Generated by Django 5.1.7 on 2025-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('cell', models.CharField(blank=True, max_length=50, null=True)),
                ('center', models.CharField(blank=True, max_length=50, null=True)),
                ('laboratory', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
