# Generated by Django 5.1.7 on 2025-03-30 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_no', models.CharField(max_length=50)),
                ('volume_no', models.CharField(blank=True, max_length=50, null=True)),
                ('security_classification', models.CharField(choices=[('confidential', 'Confidential'), ('restricted', 'Restricted'), ('public', 'Public')], max_length=20)),
                ('request_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EnclosureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/enclosures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosure_files', to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/forms/')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_files', to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_no', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approver_id', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
        ),
    ]
