# Generated by Django 5.1.7 on 2025-03-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='userid',
            new_name='user_id',
        ),
    ]
