# Generated by Django 5.1.7 on 2025-03-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('requests', '0002_rename_userid_request_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='upload_form',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='RequestApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_no', models.PositiveIntegerField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='requests.request')),
            ],
        ),
    ]
