# Generated by Django 5.1.7 on 2025-04-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('requests', '0003_rename_user_id_request_user_request_upload_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestapprover',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='enclosurefile',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='requestformfile',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='upload_form',
        ),
        migrations.RemoveField(
            model_name='requestapprover',
            name='approver_no',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='approver_id',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='approver_no',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='request_id',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='requests.request'),
            preserve_default=False,
        ),
    ]
