# Generated by Django 5.1.7 on 2025-04-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_requestapprover_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestApprover',
        ),
    ]
