# Generated by Django 5.1.7 on 2025-04-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('requests', '0005_delete_requestapprover'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='requests.request')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
