# Generated by Django 5.1.7 on 2025-04-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('requests', '0006_requestapprover'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_approvals', to='authentication.userprofile'),
        ),
    ]
