# Generated by Django 5.1.7 on 2025-04-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='requests.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='resubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
