# Generated by Django 5.1.7 on 2025-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_requeststatus_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
